import fs from 'fs';
import path from 'path';

function makePdf() {
  const invoiceText = `BT
/F1 12 Tf
72 712 Td
(Invoice Number: INV-9999-2026) Tj
0 -18 Td
(Vendor Name: Acme Corp India Solutions) Tj
0 -18 Td
(Date: 2026-06-10) Tj
0 -18 Td
(Subtotal Amount: 15000.00) Tj
0 -18 Td
(GST Rate: 18%) Tj
0 -18 Td
(CGST Amount: 1350.00) Tj
0 -18 Td
(SGST Amount: 1350.00) Tj
0 -18 Td
(Tax Amount: 2700.00) Tj
0 -18 Td
(Total Amount: 17700.00) Tj
ET`;

  // Standardize line endings to LF only for predictable byte counting
  const cleanInvoiceText = invoiceText.replace(/\r\n/g, '\n');
  const textBuffer = Buffer.from(cleanInvoiceText, 'utf8');

  const header = Buffer.from('%PDF-1.4\n', 'utf8');
  
  const obj1 = Buffer.from('1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj\n', 'utf8');
  const obj2 = Buffer.from('2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj\n', 'utf8');
  const obj3 = Buffer.from('3 0 obj\n<< /Type /Page /Parent 2 0 R /Resources << /Font << /F1 4 0 R >> >> /MediaBox [0 0 612 792] /Contents 5 0 R >>\nendobj\n', 'utf8');
  const obj4 = Buffer.from('4 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj\n', 'utf8');
  
  const obj5Prefix = Buffer.from(`5 0 obj\n<< /Length ${textBuffer.length} >>\nstream\n`, 'utf8');
  const obj5Suffix = Buffer.from('\nendstream\nendobj\n', 'utf8');
  const obj5 = Buffer.concat([obj5Prefix, textBuffer, obj5Suffix]);

  const objects = [obj1, obj2, obj3, obj4, obj5];
  
  let currentOffset = header.length;
  const offsets: number[] = [];
  
  for (const obj of objects) {
    offsets.push(currentOffset);
    currentOffset += obj.length;
  }

  const xrefOffset = currentOffset;
  
  let xrefString = 'xref\n0 6\n0000000000 65535 f \n';
  for (const offset of offsets) {
    xrefString += String(offset).padStart(10, '0') + ' 00000 n \n';
  }
  const xref = Buffer.from(xrefString, 'utf8');

  const trailer = Buffer.from(`trailer\n<< /Size 6 /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF\n`, 'utf8');

  const finalPdf = Buffer.concat([header, ...objects, xref, trailer]);

  const dest = path.resolve(__dirname, '../test_invoice.pdf');
  fs.writeFileSync(dest, finalPdf);
  console.log(`Generated byte-perfect PDF invoice at: ${dest} (Size: ${finalPdf.length} bytes)`);
}

makePdf();
